### ISSUE TITLE
admin login not working

### ISSUE THREAD

**Issue by defo89** [ryanmerolle/netbox-vagrant#1]
Based on create_user documentation the order is following: 
`create_superuser(username, email, password, **extra_fields) `

[https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.UserManager.create_user](url)

Step 16 should look like this:
`echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python /opt/netbox/netbox/manage.py shell`

**Comment by ryanmerolle** [comment]
Fixed with commit b81002f3a8b814f92446c66ee25c8adcbe453438

It seems you raised the issue while I was pushing.  Thanks!
